<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RhodiumVault</AssemblyName>
    <RootNamespace>RhodiumVault</RootNamespace>
    <Product>Rhodium Vault</Product>
    <AssemblyTitle>Rhodium Vault</AssemblyTitle>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="tests\**" />
    <None Remove="tests\**" />
    <Page Remove="tests\**" />
    <EmbeddedResource Remove="tests\**" />
  </ItemGroup>
</Project>

